export interface SuratPayload {
  id_surat?: number | null;
  nomor_surat?: string | null;
  jenis_surat: string;
  tanggal_pengajuan?: string | null;
  tanggal_disetujui?: string | null;
  nik_pemohon?: string | null;
  keperluan?: string | null;
  status_surat?: string;
  catatan?: string | null;
  attachment_bukti_pendukung?: File[] | null; // Updated to support File array
  nik_penduduk_meninggal?: string | null;
  alamat_terakhir_meninggal?: string | null;
  tanggal_kematian?: string | null;
  waktu_kematian?: string | null;
  tempat_kematian?: string | null;
  penyebab_kematian?: string | null;
  hubungan_pelapor_kematian?: string | null;
  alamat_tujuan?: string | null;
  rt_tujuan?: string | null;
  rw_tujuan?: string | null;
  kelurahan_desa_tujuan?: string | null;
  kecamatan_tujuan?: string | null;
  kabupaten_kota_tujuan?: string | null;
  provinsi_tujuan?: string | null;
  alasan_pindah?: string | null;
  klasifikasi_pindah?: string | null;
  data_pengikut_pindah?: string | null;
  nama_bayi?: string | null;
  tempat_dilahirkan?: string | null;
  tempat_kelahiran?: string | null;
  tanggal_lahir_bayi?: string | null;
  waktu_lahir_bayi?: string | null;
  jenis_kelamin_bayi?: string | null;
  jenis_kelahiran?: string | null;
  anak_ke?: number | string | null;
  penolong_kelahiran?: string | null;
  berat_bayi_kg?: number | string | null;
  panjang_bayi_cm?: number | string | null;
  nik_penduduk_ibu?: string | null;
  nik_penduduk_ayah?: string | null;
  nik_penduduk_pelapor_lahir?: string | null;
  hubungan_pelapor_lahir?: string | null;
  nama_usaha?: string | null;
  jenis_usaha?: string | null;
  alamat_usaha?: string | null;
  status_bangunan_usaha?: string | null;
  perkiraan_modal_usaha?: number | string | null;
  perkiraan_pendapatan_usaha?: number | string | null;
  jumlah_tenaga_kerja?: number | string | null;
  sejak_tanggal_usaha?: string | null;
  penghasilan_perbulan_kepala_keluarga?: number | string | null;
  pekerjaan_kepala_keluarga?: string | null;
  nik_penduduk_siswa?: string | null;
  nama_sekolah?: string | null;
  nisn_siswa?: string | null;
  kelas_siswa?: string | null;
  nomor_ktp_hilang?: string | null;
  tanggal_perkiraan_hilang?: string | null;
  lokasi_perkiraan_hilang?: string | null;
  kronologi_singkat?: string | null;
  nomor_laporan_polisi?: string | null;
  tanggal_laporan_polisi?: string | null;
  deleted_at?: string | null;
  nama_pemohon?: string | null;
  tempat_lahir_pemohon?: string | null;
  status_perkawinan_pemohon?: string | null;
  tanggal_lahir_pemohon?: string | null;
  jenis_kelamin_pemohon?: string | null;
  alamat_pemohon?: string | null;
  umur_pemohon?: number | null;
  nama_meninggal?: string | null;
  nik_meninggal?: string | null;
  tempat_lahir_meninggal?: string | null;
  tanggal_lahir_meninggal?: string | null;
  jenis_kelamin_meninggal?: string | null;
  umur_saat_meninggal?: number | null;
  hari_kematian?: string | null;
  nama_ibu?: string | null;
  umur_ibu_saat_kelahiran?: number | null;
  nama_ayah?: string | null;
  umur_ayah_saat_kelahiran?: number | null;
  nama_siswa?: string | null;
  tempat_lahir_siswa?: string | null;
  tanggal_lahir_siswa?: string | null;
  jenis_kelamin_siswa?: string | null;
  umur_siswa?: number | null;
  nomor_kk_hilang?: string | null;
  deskripsi_keperluan?: string | null;
} 